
/**
 * A service to handle collecting page metadata to be rendered into the <head>
 * of the page.
 */
module.exports = class PageMetadataService {

    constructor(core) {
        this.database = core.database
        this.logger = core.logger
        this.config = core.config


        this.baseMetadata = {
            url: core.config.host,
            applicationName: "Peer Review",
            title: "Peer Review (beta) - A Universal PrePrint+ Platform",
            description: "Peer Review is an experimental scholarly publishing platform. It enables crowdsourced peer review and public dissemination of scientific and academic papers.  It is open source and diamond open access.",
            image: `${core.config.host}img/how-it-works/review-example-2.png`,
            twitterHandle: "@peerreviewio",
            type: "website"
        }
    }

    /**
     * Get the base metadata for the root ('/') page.
     *
     * @return {Object} An object with the appropriate metadata.  See
     * constructor for object structure.
     */
    getRoot() {
        return this.baseMetadata
    }

    /**
     * Get the base metadata object for the ('/') page with development assets
     * generated by webpack-dev-middleware included.
     *
     * DEVELOPMENT ONLY.  This method is intended to be used in development
     * environments with webpack-dev-middleware only.
     *
     * @param {Object} assetsByChunkName    The hash of asset arrays by chunk
     * name returned from webpack-dev-middleware in the server side rendering
     * handler.
     *
     * @return {object} The metadata object populated with development assets.
     */
    getRootWithDevAssets(assetsByChunkName) {
        const metadata = { ...this.baseMetadata }
        
        const devAssets = []
        for(const asset of assetsByChunkName.main) {
            devAssets.push(`<script defer="defer" src="${this.config.host}${asset}"></script>`)
        }

        metadata.devAssets = devAssets 
        return metadata
    }
}
