apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-review-workers-deployment
  labels: 
    application: peer-review
    function: workers 
    environment: staging
spec:
  selector:
    matchLabels:
      application: peer-review
      function: workers 
      environment: staging
  replicas: 1
  template: 
    metadata:
      name: peer-review-workers-pod-template
      labels:
        application: peer-review
        function: workers 
        environment: staging
        container: peerreview
    spec:
      terminationGracePeriodSeconds: 600 
      containers:
        - name: peer-review-workers-container
          image: ghcr.io/danielbingham/peerreview-worker:0.2.6
          resources:
            requests:
              cpu: 100m
          env:
            - name: DEBUG
              value: "peer-review:*"
            - name: NODE_ENV
              value: staging
            - name: LOG_LEVEL
              value: debug 
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: port
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: username
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: password
                  optional: false
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: peer-review-session-secret
                  key: session_secret
                  optional: false
            - name: S3_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: peer-review-s3-credentials
                  key: access_id
                  optional: false
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: peer-review-s3-credentials
                  key: access_key
                  optional: false
            - name: POSTMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: peer-review-postmark-secrets
                  key: api_token 
                  optional: false
            - name: REDIS_HOST
              value: peer-review-staging-cache-redis-cluster.sh2hpr.0001.use1.cache.amazonaws.com
            - name: REDIS_PORT
              value: '6379'

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: peer-review-workers 
  labels:
    application: peer-review
    function: workers
    environment: staging
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peer-review-workers-deployment 
  minReplicas: 1
  maxReplicas: 4 
  targetCPUUtilizationPercentage: 50
