apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-review-redis-deployment
  labels: 
    application: peer-review
    function: redis 
    environment: local
spec:
  selector:
    matchLabels:
      application: peer-review
      function: redis 
      environment: local
  replicas: 1
  template: 
    metadata:
      name: peer-review-redis-pod-template
      labels:
        application: peer-review
        function: redis 
        environment: local
        container: peer-sql 
    spec:
      containers:
        - name: peer-review-redis-container
          image: redis
          ports:
            - containerPort: 6379 
          resources:
            limits:
              cpu: 200m 
              memory: 256M 
          imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: peer-review-redis
spec:
  selector:
    application: peer-review
    function: redis 
    environment: local
  ports:
    - protocol: TCP
      port: 6379 
      targetPort: 6379 



