apiVersion: apps/v1
kind: Deployment
metadata:
  name: peer-review-app-deployment
  labels: 
    application: peer-review
    function: frontend-api 
    environment: production
spec:
  selector:
    matchLabels:
      application: peer-review
      function: frontend-api 
      environment: production
  replicas: 2
  template: 
    metadata:
      name: peer-review-app-pod-template
      labels:
        application: peer-review
        function: frontend-api 
        environment: production
        container: peerreview
    spec:
      containers:
        - name: peer-review-app-container
          image: ghcr.io/danielbingham/peerreview:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
          env:
            - name: DEBUG
              value: "peer-review:*"
            - name: NODE_ENV
              value: production
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: host
                  optional: false
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: port
                  optional: false
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: username
                  optional: false
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: peer-review-database-credentials
                  key: password
                  optional: false
            - name: SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: peer-review-session-secret
                  key: session_secret
                  optional: false
            - name: S3_ACCESS_ID
              valueFrom:
                secretKeyRef:
                  name: peer-review-s3-credentials
                  key: access_id
                  optional: false
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: peer-review-s3-credentials
                  key: access_key
                  optional: false
            - name: ORCID_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: peer-review-orcid-secrets
                  key: client_id
                  optional: false
            - name: ORCID_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: peer-review-orcid-secrets
                  key: client_secret
                  optional: false
            - name: POSTMARK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: peer-review-postmark-secrets
                  key: api_token 
                  optional: false

---
apiVersion: v1
kind: Service
metadata:
  name: peer-review-app-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:843012963492:certificate/765e3fe5-68e0-4ba6-93d2-49d1d3d2c9ef
spec:
  type: NodePort 
  selector:
    application: peer-review
    function: frontend-api
    environment: production
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 8080
    - name: https
      protocol: TCP
      port: 443 
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: peer-review-app-ingress 
  labels:
    application: peer-review
    function: frontend-api
    environment: production
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/load-balancer-name: peer-review-production-ingress 
    alb.ingress.kubernetes.io/certificate-arn: "arn:aws:acm:us-east-1:843012963492:certificate/765e3fe5-68e0-4ba6-93d2-49d1d3d2c9ef" 
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  ingressClassName: alb
  rules:
  - host: peer-review.io
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: peer-review-app-service
            port: 
              number: 80

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: peer-review-app 
  labels:
    application: peer-review
    function: frontend-api
    environment: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peer-review-app-deployment 
  minReplicas: 2
  maxReplicas: 30 
  targetCPUUtilizationPercentage: 70
