/******************************************************************************
 * Staging Environment Core
 *
 * This modudle defines the core of the Peer Review staging environment.
 *
 * Depends on:
 * - Storage
 * - Certificate
 *
 * If you would like to add monitoring in to this environment, see Monitoring.
 * To launch bastions for VPC access, see Bastion.  DNS must be handled
 * manually due to being generated by Kubernetes.
 *
 * Before launching this environment, please read the README.md file and ensure
 * that all components that this module will create have not been created as
 * individual components in the `/components` directory.  Go through each
 * component in the directory and run `terraform destroy` to ensure that the
 * component has been destroyed.  Or use `terraform state mv` to move
 * components to this state file.
 *
 ******************************************************************************/

module "network" {
  source = "../../components/network"
}

module "database" {
  source = "../../components/database"

  username = var.database_username
  password = var.database_password

  # These come from the output of components/network.
  vpc_id = module.network.vpc_id 
  subnet_ids = module.network.private_subnet_ids 
}

module "cache" {
  source = "../../components/cache"

  vpc_id = module.network.vpc_id
  subnet_ids = module.network.private_subnet_ids
}

module "cluster" {
  source = "../../components/cluster"

  vpc_id = module.network.vpc_id
  private_subnet_ids = module.network.private_subnet_ids
  public_subnet_ids = module.network.public_subnet_ids
}
