import React, { useState, useEffect } from 'react'
import { useDispatch, useSelector } from 'react-redux'
import { useParams, useSearchParams, Link } from 'react-router-dom'

import { getJournalSubmissions, cleanupRequest } from '/state/journalSubmissions'
import { countReviews, cleanupRequest as cleanupReviewRequest } from '/state/reviews'

import DateTag from '/components/DateTag'
import Spinner from '/components/Spinner'

import SubmissionStatusWidget from '/components/journals/widgets/status/SubmissionStatusWidget'
import AssignmentWidget from '/components/journals/widgets/assignments/AssignmentWidget'

import './SubmissionControls.css'

/**
 * Render a list of draft papers belonging to the logged in user.
 * 
 * Must be logged in to view.
 *
 * TODO Refactor this to render drafts of papers and to take a query in props
 * so that we can reuse it for both the "reviews" page and the "my drafts"
 * page.
 *
 * @param {object} props    Standard react props object - empty.
 */
const SubmissionControls = function({ submissionId }) {

    // ======= Request Tracking =====================================

    const [requestId, setRequestId] = useState(null)
    const request = useSelector(function(state) {
        if ( requestId) {
            return state.journalSubmissions.requests[requestId]
        } else {
            return null
        }
    })

    // ======= Redux State ==========================================

    const submission = useSelector(function(state) {
        if ( state.journalSubmissions.dictionary[submissionId] ) {
            return state.journalSubmissions.dictionary[submissionId]
        } else {
            return null
        }
    })

    const paper = useSelector(function(state) {
        return state.papers.dictionary[submission.paperId]
    })


    const currentUser = useSelector(function(state) {
        return state.authentication.currentUser
    })

    // ======= Effect Handling ======================================

    const dispatch = useDispatch()

    useEffect(function() {
        if ( ! submission ) {
            throw new Error('Submission missing!')
        }
    }, [])

    // Cleanup our request.
    useEffect(function() {
        return function cleanup() {
            if ( requestId ) {
                dispatch(cleanupRequest({ requestId: requestId }))
            }
        }
    }, [ requestId ])

    // ====================== Render ==========================================

    // Don't render unless we've completed the request, otherwise we could wind
    // up rendering a list generated by a different request.

    let content = ( <Spinner /> )
    let noContent = null
    if ( request && request.state == 'fulfilled') {

        if ( content.length <= 0 ) {
            content = null
            noContent =  (<div className="empty-search">No papers to list.</div>)
        }
    } else if (request && request.state == 'failed') {
        content = null
        noContent = ( <div className="error">Attempt to retrieve drafts failed with error: { request.error }.  Please report this as a bug.</div> ) 
    }


    return (
        <div className="submission-controls">
            <div className="grid-wrapper">
                <div className="date">
                    <strong>Submitted:</strong> <DateTag timestamp={submission.createdDate} />
                </div>
                <div className="status">
                    <SubmissionStatusWidget id={submission.id} />
                </div>
                <div className="editors">
                    <AssignmentWidget type="editor" id={submission.id} /> 
                </div>
                <div className="reviewers">
                    <AssignmentWidget type="reviewer" id={submission.id} /> 
                </div>
            </div>
        </div>
    )

}

export default SubmissionControls 
