/******************************************************************************
 *
 *  JournalHub -- Universal Scholarly Publishing 
 *  Copyright (C) 2022 - 2024 Daniel Bingham 
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published
 *  by the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/>.
 *
 ******************************************************************************/
import { Core, ServiceError } from '@danielbingham/peerreview-core' 

export interface PageMetadata{
    url: string
    applicationName: string
    title: string
    description: string
    image: string
    twitterHandle: string
    type: string
    devAssets?: string[]
}

/**
 * A service to handle collecting page metadata to be rendered into the <head>
 * of the page.
 */
export class PageMetadataService {
    core: Core
    baseMetadata: PageMetadata 

    constructor(core: Core) {
        this.core = core

        this.baseMetadata = {
            url: core.config.host,
            applicationName: "JournalHub",
            title: "JournalHub (alpha) - A Universal Scholarly Publishing Platform",
            description: "JournalHub is a universal scholarly publishing platform.  It supports micropublications, pre-prints, preprint review, journal review and publishing, and post-publication review.",
            image: `${core.config.host}img/how-it-works/review-example-2.png`,
            twitterHandle: "@peerreviewio",
            type: "website"
        }
    }

    /**
     * Get the base metadata for the root ('/') page.
     *
     * @return {Object} An object with the appropriate metadata.  See
     * constructor for object structure.
     */
    getRoot(): PageMetadata{
        return this.baseMetadata
    }

    /**
     * Get the base metadata object for the ('/') page with development assets
     * generated by webpack-dev-middleware included.
     *
     * DEVELOPMENT ONLY.  This method is intended to be used in development
     * environments with webpack-dev-middleware only.
     *
     * @param {Object} assetsByChunkName    The hash of asset arrays by chunk
     * name returned from webpack-dev-middleware in the server side rendering
     * handler.
     *
     * @return {object} The metadata object populated with development assets.
     */
    getRootWithDevAssets(assetsByChunkName: any): PageMetadata {
        const metadata = { ...this.baseMetadata }
        
        const devAssets = []
        for(const asset of assetsByChunkName.main) {
            devAssets.push(`<script defer="defer" src="${this.core.config.host}${asset}"></script>`)
        }

        metadata.devAssets = devAssets 
        return metadata
    }
}
