name: CI

on:
  push:
    branches: 
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    permissions:
      contents: read 
      packages: write
    steps:
      - name: Checkout Repo 
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # Test @danielbingham/peerreview-model
      - name: Install Model Dependencies 
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./packages/model
        run: |
          npm ci

      - name: Run Model Unit Tests
        working-directory: ./packages/model
        run: |
          npm run test

      # Test @danielbingham/peerreview-backend
      - name: Install Backend Dependencies 
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./packages/backend
        run: |
          npm ci

      - name: Run Backend Unit Tests
        working-directory: ./packages/backend
        run: |
          npm run test

      # Test the worker.
      
      # Test web-application.
      - name: Install Web Application NPM Modules
        working-directory: ./web-application
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci
      - name: Copy the backend package for testing
        run: |
          rm -r ./web-application/node_modules/@danielbingham/peerreview-backend
          cp -r ./packages/backend ./web-application/node_modules/@danielbingham/peerreview-backend
      - name: Run Web Application Unit Tests
        working-directory: ./web-application
        run: | 
          npm run test

