name: Pull Request CI

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      
      - name: Checkout Monorepo
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}


      # Build and publish @danielbingham/peerreview-backend
      - name: Install Backend NPM Modules
        working-directory: ./packages/backend
        run: |
          npm ci 
      - name: Run Backend Unit Tests
        working-directory: ./packages/backend
        run: |
          npm run test

      # Test web-application, then build the docker container and push it to
      # the Github Container registry
      - name: Install Web Application NPM Modules
        working-directory: ./web-application
        env: 
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm ci 
      - name: Link the backend package for testing
        working-directory: ./web-application
        run: |
          rm -r node_modules/@danielbingham/peerreview-backend
          ln -s ../packages/backend node_modules/@danielbingham/peerreview-backend
      - name: Run Web Application Unit Tests
        working-directory: ./web-application
        run: | 
          npm run test

