name: Pull Request CI

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
      
      - name: Checkout Monorepo
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Determine Version
        run: 
          echo "VERSION=$( echo '${{ github.ref_name }}-${{ github.sha }}' | sed 's|/|-|g')" >> $GITHUB_ENV


      # Build and publish @danielbingham/peerreview-backend
      - name: Install Backend NPM Modules
        working-directory: ./packages/backend
        run: |
          npm ci 
      - name: Run Backend Unit Tests
        working-directory: ./packages/backend
        run: |
          npm run test
      - name: Version using the branch name
        working-directory: ./packages/backend
        run: |
          npm version $VERISON
      - name: Publish to Github Packages
        working-directory: ./packages/backend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish

      # Test web-application, then build the docker container and push it to
      # the Github Container registry
      - name: Install updated backend package 
        working-directory: ./web-application
        run: |
          npm install @danielbingham/peerreview-backend@$VERSION
      - name: Install Web Application NPM Modules
        working-directory: ./web-application
        run: |
          npm ci
      - name: Run Web Application Unit Tests
        working-directory: ./web-application
        run: | 
          npm run test
      - name: Build the  Web Application Docker Container
        working-directory: ./web-application
        run: |
           docker build -t ghcr.io/danielbingham/peerreview:$VERSION .
      - name: Login to Github Container Repository
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_REPOSITORY_OWNER --password-stdin
      - name: Push the newly built container to the Repostory under the $VERSION tag
        run: |
          docker push ghcr.io/danielbingham/peerreview:$VERSION

